#!/bin/zsh
# usage: loads all configs for given applications (specified in bootstrap) and sets this file in your $HOME

BKUP_FOLDER=~/.dotfiles-bak
mkdir -p $BKUP_FOLDER

#echo ====== Backing up your cfg files to $(echo $BKUP_FOLDER) =======
mv -f ~/.zsh_custom_cfg $BKUP_FOLDER/ 2>/dev/null
mv -f ~/.zshenv $BKUP_FOLDER/ 2>/dev/null
mv -f ~/.p10k.zsh $BKUP_FOLDER/ 2>/dev/null
mv -f ~/.aliases $BKUP_FOLDER/ 2>/dev/null
mv -f ~/.vimrc $BKUP_FOLDER/ 2>/dev/null
mv -f ~/.tilix $BKUP_FOLDER/ 2>/dev/null

DOTFILES_PATH=~/.dotfiles
ZSH_SRC_PATH=$DOTFILES_PATH/zsh

#echo ====== Coping new config giles ======
cp "$DOTFILES_PATH"/profile-config ~/profile-config 2>/dev/null
cp "$DOTFILES_PATH"/tilix/.tilix ~/.tilix 2>/dev/null
cp "$DOTFILES_PATH"/vim/.vimrc ~/.vimrc 2>/dev/null
cp "$DOTFILES_PATH"/vim/.vimrc ~/.ideavimrc 2>/dev/null
cp "$ZSH_SRC_PATH"/.zshrc ~/.zshrc 2>/dev/null
cp "$ZSH_SRC_PATH"/.zsh_custom_cfg ~/.zsh_custom_cfg 2>/dev/null
cp "$ZSH_SRC_PATH"/.zshenv ~/.zshenv 2>/dev/null
cp "$ZSH_SRC_PATH"/.p10k.zsh ~/.p10k.zsh 2>/dev/null
cp "$ZSH_SRC_PATH"/.aliases ~/.aliases 2>/dev/null

dconf load /com/gexperts/Tilix/ < $DOTFILES_PATH/tilix/tilix.dconf

echo profile-config updated.
